name: 2. Automated Instagram Queue


on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-queue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Process Queue
        env:
          IG_USER_ID: ${{ secrets.IG_USER_ID }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: python schedule_post.py

      - name: Commit Queue Updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add scheduled_queue.json
          git commit -m "Update queue status [skip ci]" || exit 0
          git push